apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - fstype: xfs
        name: vg1
        default: true
        thinPoolConfig:
          chunkSizeCalculationPolicy: Static
          sizePercent: 90
          name: thin-pool-1
          overprovisionRatio: 10
